[package]
name = "incircle_protocol"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "^0.11"

[build-dependencies]
prost-build = { version = "^0.11" }
